### ISSUE TITLE
Where is index.js referred in package.json?

### ISSUE THREAD

**Issue by santhoshtr** [makersofkerala/thengascript#1]

**Comment by jaisonka91** [comment]
Searching for the same, where is the main script file?

**Comment by jaisonka91** [comment]
http://bunchaeffinamateurs.com/ss/thengascript/js/demo.js

**Comment by prathyvsh** [comment]
ക്ഷമിക്കണം, കുറച്ചു പരിപാടികൾ ചെയ്തു തീർക്കാനുണ്ടായിരുന്നു. സാധനം ഇപ്പോൾ റെഡി ആയിട്ടുണ്ട്! — https://www.npmjs.com/package/thengascript
