### ISSUE TITLE
script transpiles string literals too.

### ISSUE THREAD

**Issue by shanavas786** [makersofkerala/thengascript#12]
```
console.log("ആണെങ്കിൽ")
```
prints `if`.

One solution could be to translate string to some intermediate representation before translating keywords.

**Comment by prathyvsh** [comment]
Yup. I acknowledge this bug. In the process of writing a new parser to fix this.

**Comment by ByteJoseph** [comment]
Ok ഇത് എങ്ങനെ ശരിയാക്കാൻ പറ്റും.

**Comment by prathyvsh** [comment]
> Ok ഇത് എങ്ങനെ ശരിയാക്കാൻ പറ്റും.

ഈ വാരാവസാനം സമയം ഒത്തു വരുകയാങ്കിൽ ഒന്നു പണിഞ്ഞു നോക്കാം ബ്രൊ.

**Comment by ByteJoseph** [comment]
> > Ok ഇത് എങ്ങനെ ശരിയാക്കാൻ പറ്റും.
> 
> ഈ വാരാവസാനം സമയം ഒത്തു വരുകയാങ്കിൽ ഒന്നു പണിഞ്ഞു നോക്കാം ബ്രൊ.

ഞാനും ശ്രമിക്കാം. ശരിയാകുവാണെങ്കാൽ ഇവിടെ വരാം.

**Comment by shanavas786** [comment]
പാർസിങ്ങിന്  [esprima](https://esprima.org) ഉപയോഗിച്ചൂടേ ?

**Comment by prathyvsh** [comment]
@shanavas786 പരമാവതി മറ്റുള്ള ലൈബ്രറികൾ അശ്രയിക്കാതെ തേങ്ങാസ്ക്രിപ്റ്റ് നിർമ്മിക്കാനാണ് തുടർച്ചയായ പരിശ്രമം. പക്ഷെ കേരളത്തിൽ നിന്നും ആരെങ്കിലും ഒരു ജാവാസ്ക്രിപ്റ്റ് പാർസർ എഴുതിയിട്ടുണ്ടെങ്കിൽ അതിന്റെ അനുയോജ്യത ഒന്നു വിലയിരുത്തിയ ശേഷം  ഉപയോഗിക്കാൻ ഞങ്ങൾ ഒരുക്കമാണ്!

**Comment by prathyvsh** [comment]
@its-joseph-230606 ഒരു പുതിയ പതിപ്പ് പ്രസിദ്ധീകരിച്ചിട്ടുണ്ട് (v0.1.3) ഉപയോഗിച്ച് നോക്കി അഭിപ്രായം അറിയിക്കാമോ?

**Comment by ByteJoseph** [comment]
> @its-joseph-230606 ഒരു പുതിയ പതിപ്പ് പ്രസിദ്ധീകരിച്ചിട്ടുണ്ട് (v0.1.3) ഉപയോഗിച്ച് നോക്കി അഭിപ്രായം അറിയിക്കാമോ?

Good. Issue solved
