### ISSUE TITLE
indexOf & undefined

### ISSUE THREAD

**Issue by subins2000** [makersofkerala/thengascript#13]
Need alternatives for `indexOf` and `undefined`

**Comment by subins2000** [comment]
indexOf - `ന്റെസൂചിക`
undefined - `നിർവചിച്ചിട്ടില്ല`

**Comment by prathyvsh** [comment]
@subins2000

It seems like there are at least two kinds of possessive genetives (guess they are called that) — `-ഇന്റെ ` and `-ഉടെ`:

`ന്റെസൂചിക` works for:

`shark.indexOf(teeth) ~ സ്രാവിന്റെ പല്ല്`

but doesn’t fit with:

`table.indexOf(leg) ~ മേശയുടെ കാൽ`

So guess I’ll go with സൂചിക for now.

**Comment by prathyvsh** [comment]
സൂചിക and നിർവചിച്ചിട്ടില്ല added.

**Comment by madhaven** [comment]
It would be nice if the commits referenced this issue
@prathyvsh

**Comment by prathyvsh** [comment]
@madhaven Will keep that in mind from now on. Thanks for the note.

**Comment by madhaven** [comment]
💝
