### ISSUE TITLE
Huge bug in Thengascript 0.1.4 package 

### ISSUE THREAD

**Issue by ByteJoseph** [makersofkerala/thengascript#19]
```bash
node simple.js
```

**Lines 55 and 62 in the thengascript cause the program to throw error**

![IMG_20240422_193451](https://github.com/makersofkerala/thengascript/assets/131424720/5e051d96-722b-42c9-a7f3-2356294efff3)
.

**Comment by ByteJoseph** [comment]
I will do a PR tomorrow

**Comment by prathyvsh** [comment]
This has been fixed. Please check it out and let me know.

**Comment by ByteJoseph** [comment]
> This has been fixed. Please check it out and let me know.

Ok issue solved
