### ISSUE TITLE
കോഡ് കാൺമാനില്ല

### ISSUE THREAD

**Issue by manojpramesh** [makersofkerala/thengascript#2]

**Comment by rahmathm1** [comment]
+1

**Comment by redtachyons** [comment]
http://bunchaeffinamateurs.com/ss/thengascript/js/demo.js Here is the code used for demo, basically mapping Malayalam words to js keywords, No compilation/transpilation involved

**Comment by manojpramesh** [comment]
This is great. Thank you for sharing.

**Comment by prathyvsh** [comment]
ക്ഷമിക്കണം. പോസ്റ്റ് ആക്കിയതിൽ ഖേദിക്കുന്നു.

![image](https://user-images.githubusercontent.com/760789/35743788-96e3d978-0864-11e8-8880-d715feeed918.png)

ചെറിയ ചില പരിപാടികൾ ചെയ്തു തീർക്കാനുണ്ടായിരുന്നു. സാധനം ഇപ്പ അപ്‌ലോഡ് ചെയ്തിട്ടുണ്ട്.
