### ISSUE TITLE
Main script file missing

### ISSUE THREAD

**Issue by shajanjp** [makersofkerala/thengascript#3]
I couldn't find even a single javascript file in this repo.

**Comment by jaisonka91** [comment]
http://bunchaeffinamateurs.com/ss/thengascript/js/demo.js

**Comment by prathyvsh** [comment]
![image](https://user-images.githubusercontent.com/760789/35743299-3727f95c-0863-11e8-99e5-bbf5135a5ee0.png)
സാധനം എത്തിയിട്ടുണ്ട്.

**Comment by shajanjp** [comment]
![](https://www.malayalamplainmemes.download/images/oru-mexican-aparatha-kalabhavan-shajohn-iogab/full)
