### ISSUE TITLE
not all keywords are working

### ISSUE THREAD

**Issue by AlbinShaji** [makersofkerala/thengascript#4]
![image](https://user-images.githubusercontent.com/20659935/35719495-b410e1bc-080f-11e8-886e-4ffac98f3f6f.png)

<script>
	var ക = 2;
	var ച = 4;
	
	document.write(ക + ച);
	
	function വിളി(പേര്) {
    document.write( " കമോണ്ട്രാ " + പേര് + "!");
};

 വിളി("മഹേഷേ");
	</script>
as you can see in the script even the examples you guys gave are not working in a proper way.

**Comment by sainalshah** [comment]
u have to include type="text/thengascript" with script tag.
example,
```
<script src="node_modules/thengascript/thengascript.js"></script>

<script type="text/thengascript">

var ക = 2; var ച = 4;
document.write(ക + ച);

function വിളി(പേര്) {
  document.write( " കമോണ്ട്രാ " + പേര് + "!");
}; 

വിളി("മഹേഷേ");


</script>
```

**Comment by prathyvsh** [comment]
The script has been pushed online, can you please verify if it's working now?

Update: Plan is to implement parsing using Acorn now: See https://github.com/bunchaeffinamateurs/thengascript/issues/8
