### ISSUE TITLE
Bring in better parsing

### ISSUE THREAD

**Issue by prathyvsh** [makersofkerala/thengascript#8]
I have been trying out Thengascript to build a complete application recently, and the current idea of Malayalam -> English mapping via regex as expected doesn't scale up to the job. Idea is to bring in better parsing to identify tokens and replace them.

**Comment by madhaven** [comment]
I'd like to suggest changing the grammar used in English-based code to Malayalam based grammar.
This would change the structure of the keywords in use and a simple mapping from Malayalam words to English wouldn't work.
A new grammar would need to be implemented, this could help make Malayalam code more readable and naturally understandable as well.

**Comment by prathyvsh** [comment]
> I'd like to suggest changing the grammar used in English-based code to Malayalam based grammar. This would change the structure of the keywords in use and a simple mapping from Malayalam words to English wouldn't work. A new grammar would need to be implemented, this could help make Malayalam code more readable and naturally understandable as well.

Yup. This is currently under consideration. But thinking of moving away from Javascript as a compile target to an independent language. The more we work with JS, the more we feel it is not appropriate for what we want to accomplish here. Also, as you correctly note, Malayalam grammar opens up a vast field for creating innovative grammars well adapted to the language. Might take that up in the new language we make.
